version: '3'
services:
  # Rubyの設定
  rails:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile  # rubyディレクトリ内のDockerfileを指定
    environment:
      # --ここからDBがMySQLの場合の記述--
        # RAILS_ENV: "development"
        # MYSQL_USER: "root"
        # MYSQL_PASSWORD: "example_root_password"
        # MYSQL_HOST: "mysql"
      # --ここまでDBがMySQLの場合の記述--

      # --ここからDBがPostgreSQLの場合の記述--
        POSTGRESQL_USER: "postgres_master"
        POSTGRESQL_PASSWORD: "postgres_password"
        POSTGRESQL_HOST: "postgresql"
      # --ここまでDBがPostgreSQLの場合の記述--

    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on: # serviseの起動順序を指定
      # - mysql # DB立ち上げ後にrailsが起動するように指定
      - postgresql
    ports:
      - "3000:3000" # ホスト環境ポート:コンテナ内部ポート
    volumes:
      - ./sample_rails_application:/app
      - bundle_data:/usr/local/bundle

  # # MySQLの設定
  # mysql:
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "example_root_password"
  #     MYSQL_USER: "sample_user"
  #     MYSQL_PASSWORD: "sample_password"
  #     MYSQL_DATABASE: "sample_rails_db"
  #     TZ: 'Asia/Tokyo'
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "33306:3306"

  # PostgreSQLの設定
  postgresql:
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_USER: "postgres_master"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# データ永続化領域
volumes:
  bundle_data:
  # mysql_data:
  pg_data: